#!/usr/bin/env python3
"""Wearable Node Schematic Generator — C13B0 Structural Engine"""

nodes = {
    "SensorNode": {
        "compute": "ARM Cortex M0+ (ultra-low-power)",
        "memory": "8MB NOR Flash",
        "harvest": "Thermoelectric (chest/back)",
        "bus": "Cu-CNT yarn mesh",
        "shield": "Conductive carbon weave",
        "thermal": "Graphene dissipation strip",
        "placement": "Distributed — skin contact points",
    },
    "ComputeNode": {
        "compute": "RISC-V RV32IMC (neuromorphic mode)",
        "memory": "32MB MRAM (non-volatile)",
        "harvest": "Thermoelectric + RF rectenna",
        "bus": "Cu-CNT yarn mesh (high bandwidth)",
        "shield": "Mu-metal + carbon fiber",
        "thermal": "Graphene heat spreader + phase-change pad",
        "placement": "Upper back (heat sink area)",
    },
    "PowerNode": {
        "compute": "Dedicated PMIC controller",
        "memory": "2MB config Flash",
        "harvest": "Piezo (shoe) + Solar (shoulder panel)",
        "bus": "Power distribution yarn",
        "shield": "Insulated carbon sheath",
        "thermal": "Passive copper trace dissipation",
        "placement": "Shoes (piezo), shoulders (solar)",
    },
    "MeshRouter": {
        "compute": "BLE 5.3 SoC (nRF54)",
        "memory": "4MB Flash + 512KB SRAM",
        "harvest": "Parasitic from bus power",
        "bus": "Cu-CNT mesh + BLE radio",
        "shield": "RF-transparent carbon weave",
        "thermal": "Ambient convection",
        "placement": "Limb junctions (wrist, ankle, waist)",
    },
}

# Generator placement mapping
placement_map = {
    "Shoes":     {"harvest": "Piezoelectric",  "power": "5-50 uW/step",   "notes": "Impact harvesting, gait-dependent"},
    "Back":      {"harvest": "Solar (flex)",    "power": "10-100 mW/panel","notes": "Outdoor only, angle-dependent"},
    "Chest":     {"harvest": "Thermoelectric",  "power": "10-100 uW",     "notes": "Best dT, stable skin contact"},
    "Shoulders": {"harvest": "RF rectenna",     "power": "1-10 uW",       "notes": "Ambient RF, highly variable"},
    "Wrist":     {"harvest": "Piezo + thermo",  "power": "5-30 uW",       "notes": "Motion + moderate dT"},
}

# Generate schematics markdown
output = "# C13B0 Wearable Node Schematics\n\n"
output += "Generated by the Infinity Structural Engine\n\n"
output += "---\n\n"

for name, spec in nodes.items():
    output += f"## {name}\n\n"
    output += "| Parameter | Specification |\n"
    output += "|-----------|---------------|\n"
    for key, val in spec.items():
        output += f"| {key.capitalize()} | {val} |\n"
    output += "\n---\n\n"

output += "## Energy Harvest Placement Map\n\n"
output += "| Body Zone | Harvest Type | Power Range | Notes |\n"
output += "|-----------|-------------|-------------|-------|\n"
for zone, info in placement_map.items():
    output += f"| {zone} | {info['harvest']} | {info['power']} | {info['notes']} |\n"

output += "\n---\n\n"
output += "## Design Constraints\n\n"
output += "- Total wearable power budget: ~200 uW (realistic body harvest)\n"
output += "- Must support MCU sleep mode indefinitely\n"
output += "- Active compute bursts: max 10ms every 10s\n"
output += "- BLE beacon: 1 packet/second max\n"
output += "- All materials biocompatible (no lead, cadmium)\n"
output += "- Washable: sealed nodes with flex interconnects\n"

print(output)

# Write to file
with open("schematics/node_schematics.md", "w") as f:
    f.write(output)
    print("\nWritten to schematics/node_schematics.md")
